### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by christofarn** [azeam/camset#13]
Thanks a lot for camset - I could successfully install it on a debian and really like it.
When trying to install it on a ubuntu machine, I got this:

~$ pip3 install camset
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/home/sina/.local/lib/python3.5/site-packages/pip/__init__.py", line 12, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/home/sina/.local/lib/python3.5/site-packages/pip/_internal/utils/entrypoints.py", line 4, in <module>
    from pip._internal.cli.main import main
  File "/home/sina/.local/lib/python3.5/site-packages/pip/_internal/cli/main.py", line 58
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
~$ 

(I did "pip3 install --upgrade setuptools pip" before, as I needed to do so for my installation on debian)

**Comment by christofarn** [comment]
I see, this is a pip issue - caused by using an old python version - sorry for disturbing!
